### PR TITLE
Add one page website for parsec

### PR DESCRIPTION
**Pull request by celestehorgan**

### CODE REVIEW

**Comment by nineinchnail** [comment]
Hi Celeste, 

I think we need to work in emails since our marketing team is not setup to work in Github.   We have sent a few email replies to the github email that provides the message, but I don't think you are receiving them.  Can you email me directly: marc.meunier@arm.com   

Thanks,
Marc

**Comment by nineinchnail** [comment]
Hi Celeste, 

We are still quite eager to connect and kick off the site.   Let me know if you receive this message and if we can connect early next week to discuss next steps. 

Thanks,
Marc

**Comment by celestehorgan** [comment]
Hi @nineinchnail!

Awesome! I've reached out via the CNCF Service desk ticket with my email address. Please check that and we'll connect.

Cheers,
Celeste

**Comment by celestehorgan** [comment]
@nineinchnail – latest changes updated, care to review?

**Comment by ckadiyala** [comment]
@celestehorgan is this still the staging site to review? https://deploy-preview-1--parallaxsecond.netlify.app/

**Comment by celestehorgan** [comment]
@ckadiyala – yes, this is the staging for review

**Comment by ckadiyala** [comment]
@celestehorgan We need few changes to the page before this can go live.

1) Add two new partner logos to the list. Both logos attached below. Also, in the partner list under Arm logo, can you spell that as "Arm" instead of ARM.
2) In terms of branding, it's officially called Parsec instead of PARSEC. This however does not apply to the logo of the project, so n o need to update the  Parsec logos on the site. There are few places that needs to be updated to "Parsec" naming convention on the site.

- In the opening description at the top, "PARSEC is the Platform AbstRaction for SECurity....."
- In the "Learn more about Parsec" videos section. The individual bullets has PARSEC repeated multiple times. Can you please update that to Parsec.

Nixu_CyberSecurity_logo
openSuse

Thanks!

**Comment by ckadiyala** [comment]
@celestehorgan thanks for the updates. The changes looks great. One nitpick change - is it possible to resize the docker and red hat logos so they are consistent with other logos in the collaborator section? That is the only change and we can go ahead and publish the changes live. Let me know the process to get the website published to the new domain that we secured.

**Comment by celestehorgan** [comment]
@ckadiyala – check again!

**Pull request merged**
