### PR TITLE
Adding .github/settings.yml.

### PR DESCRIPTION
**Pull request by nate-double-u**
Setting repo defaults, labels

Adding @caniszczyk, @amye as admins

Adding @chalin & @nate-double-u as maintainers

Adding .gitignore file

Removing unneeded files

### CODE REVIEW

**Comment by nate-double-u** [comment]
hold, copy paste errors.

**Comment by nate-double-u** [comment]
unhold, errors corrected.

**Comment by nate-double-u** [comment]
If we agree this is the way to go for access, @nineinchnail would you like me to add you as well? (you can also add yourself once it's merged, but it might be easier to get it all done right off the hop)

**Comment by nineinchnail** [comment]
that sounds good Nate! 

Thanks,
Marc

**Comment by nate-double-u** [comment]
In order for this to work, I think that one of the org maintainers will need to add the [GitHub settings app](https://github.com/apps/settings).

**Pull request merged**
